language: cpp
compiler:
- gcc
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
install:
- wget http://www.biicode.com/downloads/latest/ubuntu64
- mv ubuntu64 bii-ubuntu64.deb
- (sudo dpkg -i bii-ubuntu64.deb) && sudo apt-get -f install
- rm bii-ubuntu64.deb
- wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
- tar -xzf cmake-3.0.2-Linux-64.tar.gz
- sudo cp -fR cmake-3.0.2-Linux-64/* /usr
- rm -rf cmake-3.0.2-Linux-64
- rm cmake-3.0.2-Linux-64.tar.gz
script:
- cmake --version
- bii init strayflux
- mkdir -p ./strayflux/blocks/strayfluxinteractive/strayflux
- mv !(strayflux) ./strayflux/blocks/strayfluxinteractive/strayflux
- cd strayflux
- bii find -um
- bii cpp:build
- cd bin
- ./strayfluxinteractive_strayflux_test_main
after_success:
- bii user strayfluxinteractive -p $BII_strayfluxinteractive_PASSWORD
- bii publish

addons:
  coverity_scan:
    project:
      name: "strayfluxinteractive/strayflux"
    notification_email: zephyrz2712@gmail.com
    build_command: script
    branch_pattern: coverity_scan

env:
  global:
    # Biicode
    - secure: "m1mVjRT0GHZFiU3Q3b7ja0zGJ/iv52A7Bm6Yb7PFJRItwu086AZXVdQ527a0luCtDyN72jWzjsPrk63hh8bejTB/HFjzeUu3evXCr1sAz383FYeB1aX6wSGPJZDfWId9bDrr3K0hvQyZZLf/0LIDwuLcZV01EwLMFskwHTVkUqU="
    # Coverity
    - secure: "ltR85Gfh9gcDbj3LdVHlRzZKIaf9HtKKXjDAaUnEsmKQKFCjnK2kmg9g+GZdTjgeVZpNyVUDIh1WtYqJ7xEjt/7xTzDiBBBlIVYWjV6hoN08QRTHrwlE4ChMU36ci+ib1FgzsPBrPEJeFc6J+GeXQ6GcsNZLZFviSEKW15DI71k="
